users:
  Shawn:
    username: Shawn
    articleIds:
      - 3
    commentIds:
      - 3
      - 4
  Bob:
    username: Bob
    articleIds:
      - 2
    commentIds:
      - 2
articles:
  '1': null
  '2':
    id: 2
    title: My best
    url: www.url.com
    username: Bob
    commentIds:
      - 2
      - 3
      - 4
    upvotedBy:
      - Bob
    downvotedBy: []
    comments:
      - &ref_0
        id: 2
        body: boop
        username: Bob
        articleId: 2
        upvotedBy: []
        downvotedBy:
          - Bob
  '3':
    id: 3
    title: NEW
    url: WWW.T.com
    username: Shawn
    commentIds: []
    upvotedBy: []
    downvotedBy:
      - Shawn
nextArticleId: 4
comments:
  '1': null
  '2': *ref_0
  '3':
    id: 3
    body: it works!
    username: Shawn
    articleId: 2
    upvotedBy:
      - Shawn
    downvotedBy: []
  '4':
    id: 4
    body: this is awesome!
    username: Shawn
    articleId: 2
    upvotedBy:
      - Shawn
    downvotedBy: []
nextCommentId: 5
